"""cria schema inicial

Revision ID: dfa3097f5933
Revises:
Create Date: 2026-09-23 17:59:19.040399

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dfa3097f5933"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cliente",
        sa.Column("id_cliente", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("telefone", sa.String(length=20), nullable=False),
        sa.Column("is_ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id_cliente"),
    )
    op.create_table(
        "endereco",
        sa.Column("id_endereco", sa.Integer(), nullable=False),
        sa.Column("cidade", sa.String(length=50), nullable=False),
        sa.Column("bairro", sa.String(length=50), nullable=False),
        sa.Column("rua", sa.String(length=50), nullable=False),
        sa.Column("logradouro", sa.String(length=50), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("cep", sa.CHAR(length=8), nullable=False),
        sa.Column("is_ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id_endereco"),
    )
    op.create_table(
        "fornecedor",
        sa.Column("id_fornecedor", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=50), nullable=False),
        sa.Column("telefone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("observacao", sa.String(length=255), nullable=False),
        sa.Column("is_ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id_fornecedor"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "produto",
        sa.Column("id_produto", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("descricao", sa.String(length=255), nullable=False),
        sa.Column("preco_unitario", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("estoque_atual", sa.Integer(), nullable=False),
        sa.Column("estoque_minimo", sa.Integer(), nullable=False),
        sa.Column("is_ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id_produto"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "usuario",
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("endereco", sa.String(length=255), nullable=False),
        sa.Column("telefone", sa.String(length=20), nullable=False),
        sa.Column("senha", sa.String(length=150), nullable=False),
        sa.Column("is_ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id_usuario"),
    )
    op.create_index(op.f("ix_usuario_email"), "usuario", ["email"], unique=True)
    op.create_table(
        "cliente_endereco",
        sa.Column("id_cliente", sa.Integer(), nullable=False),
        sa.Column("id_endereco", sa.Integer(), nullable=False),
        sa.Column("apelido", sa.String(length=50), nullable=False),
        sa.Column("principal", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["id_cliente"], ["cliente.id_cliente"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["id_endereco"], ["endereco.id_endereco"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_cliente", "id_endereco"),
    )
    op.create_table(
        "fornecimento",
        sa.Column("id_produto", sa.Integer(), nullable=False),
        sa.Column("id_fornecedor", sa.Integer(), nullable=False),
        sa.Column("preco_custo_unitario", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("numero_nota_fiscal", sa.Integer(), nullable=False),
        sa.Column("data_entrega", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_fornecedor"],
            ["fornecedor.id_fornecedor"],
        ),
        sa.ForeignKeyConstraint(
            ["id_produto"],
            ["produto.id_produto"],
        ),
        sa.PrimaryKeyConstraint("id_produto", "id_fornecedor"),
    )
    op.create_table(
        "movimentacoes",
        sa.Column("id_movimentacao", sa.Integer(), nullable=False),
        sa.Column("tipo_movimentacao", sa.String(length=20), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("tipo_referencia", sa.String(length=20), nullable=False),
        sa.Column(
            "data_movimentacao",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id_produto", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_produto"],
            ["produto.id_produto"],
        ),
        sa.PrimaryKeyConstraint("id_movimentacao"),
    )
    op.create_table(
        "vendas",
        sa.Column("id_venda", sa.Integer(), nullable=False),
        sa.Column("data_venda", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valor_total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("forma_pagamento", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("observacao", sa.String(length=255), nullable=False),
        sa.Column("data_pagamento", sa.DateTime(timezone=True), nullable=False),
        sa.Column("canal_envio", sa.String(length=30), nullable=False),
        sa.Column("id_cliente", sa.Integer(), nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_cliente"],
            ["cliente.id_cliente"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["usuario.id_usuario"],
        ),
        sa.PrimaryKeyConstraint("id_venda"),
    )
    op.create_table(
        "item_vendas",
        sa.Column("id_venda", sa.Integer(), nullable=False),
        sa.Column("id_produto", sa.Integer(), nullable=False),
        sa.Column("preco_unitario", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_produto"],
            ["produto.id_produto"],
        ),
        sa.ForeignKeyConstraint(["id_venda"], ["vendas.id_venda"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_venda", "id_produto"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item_vendas")
    op.drop_table("vendas")
    op.drop_table("movimentacoes")
    op.drop_table("fornecimento")
    op.drop_table("cliente_endereco")
    op.drop_index(op.f("ix_usuario_email"), table_name="usuario")
    op.drop_table("usuario")
    op.drop_table("produto")
    op.drop_table("fornecedor")
    op.drop_table("endereco")
    op.drop_table("cliente")
    # ### end Alembic commands ###
